### ISSUE TITLE
tvOS Safe Area Guides Bug

### ISSUE THREAD

**Issue by loganblevins** [googleads/swift-package-manager-google-interactive-media-ads-tvos#5]
Related to https://groups.google.com/g/ima-sdk/c/n8NCnaAtAko .

Ad UI is inset to safe areas now and this framework is totally unusable

**Comment by gschoppe** [comment]
Issues related to the SDK itself, rather than the SPM package, are best directed to the [IMA SDK google group](https://groups.google.com/g/ima-sdk/). That said, our engineers are aware of the issue and are currently working on a solution.
